-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- SYOUUBIN_LIST Table Create SQL
CREATE TABLE SYOUUBIN_LIST
(
    TYUUMON_ID     NUMBER    NOT NULL, 
    SYOUBINN_ID    NUMBER    NOT NULL
)
/


-- SYOUUBIN_LIST Table Create SQL
CREATE TABLE PRODUCER
(
    PRODUCER_ID    VARCHAR2(20)     NOT NULL, 
    PW             VARCHAR2(20)     NOT NULL, 
    NAME           VARCHAR2(15)     NOT NULL, 
    ADRESS         VARCHAR2(150)    NULL, 
    PHONE          VARCHAR2(13)     NULL, 
    CONSTRAINT PRODUCER_PK PRIMARY KEY (PRODUCER_ID)
)
/


-- SYOUUBIN_LIST Table Create SQL
CREATE TABLE CONSUMER
(
    CONSUMER_ID    VARCHAR2(20)     NOT NULL, 
    PW             VARCHAR2(20)     NOT NULL, 
    NAME           VARCHAR2(15)     NOT NULL, 
    ADRESS         VARCHAR2(150)    NULL, 
    PHONE          VARCHAR2(13)     NULL, 
    CONSTRAINT CONSUMER_PK PRIMARY KEY (CONSUMER_ID)
)
/


-- SYOUUBIN_LIST Table Create SQL
CREATE TABLE SYOUBINN
(
    SYOUBINN_ID    NUMBER           NOT NULL, 
    NAME           VARCHAR2(15)     NOT NULL, 
    SYUURUI        VARCHAR2(150)    NULL, 
    PRICE          NUMBER           NOT NULL, 
    PRODUCER_ID    VARCHAR2(20)     NOT NULL, 
    S_INDATE       DATE             NOT NULL, 
    CONSTRAINT SYOUBINN_PK PRIMARY KEY (SYOUBINN_ID)
)
/

CREATE SEQUENCE SYOUBINN_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER SYOUBINN_AI_TRG
BEFORE INSERT ON SYOUBINN 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT SYOUBINN_SEQ.NEXTVAL
    INTO :NEW.SYOUBINN_ID
    FROM DUAL;
END;
/

--DROP TRIGGER SYOUBINN_AI_TRG;
/

--DROP SEQUENCE SYOUBINN_SEQ;
/

ALTER TABLE SYOUBINN
    ADD CONSTRAINT FK_SYOUBINN_PRODUCER_ID_PRODUC FOREIGN KEY (PRODUCER_ID)
        REFERENCES PRODUCER (PRODUCER_ID)
/

ALTER TABLE SYOUBINN
    ADD CONSTRAINT FK_SYOUBINN_SYOUBINN_ID_SYOUUB FOREIGN KEY (SYOUBINN_ID)
        REFERENCES SYOUUBIN_LIST (SYOUBINN_ID)
/


-- SYOUUBIN_LIST Table Create SQL
CREATE TABLE TYUUMON
(
    TYUUMON_ID     NUMBER          NOT NULL, 
    CONSUMER_ID    VARCHAR2(20)    NOT NULL, 
    T_INDATE       DATE            NOT NULL, 
    CONSTRAINT TYUUMON_PK PRIMARY KEY (TYUUMON_ID)
)
/

CREATE SEQUENCE TYUUMON_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TYUUMON_AI_TRG
BEFORE INSERT ON TYUUMON 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TYUUMON_SEQ.NEXTVAL
    INTO :NEW.TYUUMON_ID
    FROM DUAL;
END;
/

--DROP TRIGGER TYUUMON_AI_TRG;
/

--DROP SEQUENCE TYUUMON_SEQ;
/

ALTER TABLE TYUUMON
    ADD CONSTRAINT FK_TYUUMON_CONSUMER_ID_CONSUME FOREIGN KEY (CONSUMER_ID)
        REFERENCES CONSUMER (CONSUMER_ID)
/

ALTER TABLE TYUUMON
    ADD CONSTRAINT FK_TYUUMON_TYUUMON_ID_SYOUUBIN FOREIGN KEY (TYUUMON_ID)
        REFERENCES SYOUUBIN_LIST (TYUUMON_ID)
/


