DROP TABLE BOOK;
CREATE TABLE BOOK(
BNUM NUMBER PRIMARY KEY,
TITLE VARCHAR2(50) NOT NULL,
AUTHOR VARCHAR2(50) NOT NULL,
PUBLISHER VARCHAR2(50) NOT NULL,
TYPE VARCHAR2(10) NOT NULL,
PRICE NUMBER DEFAULT 0,
INPUTDATE DATE DEFAULT SYSDATE
);

DROP SEQUENCE BNUM_SEQ;
CREATE SEQUENCE BNUM_SEQ;

DROP TRIGGER BNUM_TRI;
CREATE OR REPLACE TRIGGER BNUM_TRI
BEFORE INSERT ON BOOK FOR EACH ROW
    BEGIN
    SELECT BNUM_SEQ.NEXTVAL
    INTO :NEW.BNUM
    FROM DUAL;
END;
    