DROP TABLE CONSUMER;
CREATE TABLE CONSUMER(
CONSUMER_ID VARCHAR2(20) ,
CONSUMER_NAME VARCHAR2(20),
PROPERTY NUMBER DEFAULT 50000,
CONSTRAINT PK2 PRIMARY KEY(CONSUMER_ID, CONSUMER_NAME)
);

DROP TABLE PRODUCER;
CREATE TABLE PRODUCER(
PRODUCER_ID VARCHAR2(20) UNIQUE ,
PRODUCER_NAME VARCHAR2(20),
PROPERTY NUMBER DEFAULT 100000,
CONSTRAINT PK PRIMARY KEY(PRODUCER_ID, PRODUCER_NAME)
);

DROP TABLE MOVIE;
CREATE TABLE MOVIE(
MOVIE_NUM NUMBER PRIMARY KEY,
MOVIE_NAME VARCHAR2(20),
SEKI NUMBER,
PRICE NUMBER,
PRODUCER_ID VARCHAR2(20) UNIQUE,
PRODUCER_NAME VARCHAR2(20),
FOREIGN KEY (PRODUCER_ID, PRODUCER_NAME)REFERENCES PRODUCER(PRODUCER_ID, PRODUCER_NAME) ON DELETE SET NULL 
);

ALTER TABLE MOVIE MODIFY(SEKI NUMBER DEFAULT 5);

DELETE SEQUENCE MOVIE_SEQ;
CREATE SEQUENCE MOVIE_SEQ;
CREATE OR REPLACE TRIGGER MOVIE_TRI
    BEFORE INSERT ON MOVIE FOR EACH ROW
    BEGIN
    SELECT MOVIE_SEQ.NEXTVAL
    INTO :NEW.MOVIE_NUM
    FROM DUAL;
END;



DROP TABLE BIDGE;
CREATE TABLE BIDGE(
MOVIE_NUM NUMBER,
FOREIGN KEY(MOVIE_NUM) REFERENCES MOVIE(MOVIE_NUM) ON DELETE CASCADE,
CONSUMER_ID VARCHAR2(20) ,
CONSUMER_NAME VARCHAR2(20),
FOREIGN KEY(CONSUMER_ID, CONSUMER_NAME) REFERENCES CONSUMER(CONSUMER_ID, CONSUMER_NAME) ON DELETE CASCADE
);

DROP TABLE REPLY;
CREATE TABLE REPLY(
REPLY_NUM NUMBER PRIMARY KEY,
CONTENTS VARCHAR2(1000),
MOVIE_NUM NUMBER,
CONSUMER_ID VARCHAR2(20),
FOREIGN KEY(REPLY_NUM) REFERENCES REPLY(REPLY_NUM)
);

DELETE SEQUENCE REPLY_SEQ;
CREATE SEQUENCE REPLY_SEQ;
CREATE OR REPLACE TRIGGER REPLY_TRI
BEFORE INSERT ON REPLY FOR EACH ROW
BEGIN
    SELECT REPLY_SEQ.NEXTVAL
    INTO :NEW.REPLY_NUM
    FROM DUAL;
END;